spring.application.name=ReactJS_CRUD

# Server Port
server.port=8086

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/Emplyee_CRUD
spring.datasource.username=postgres
spring.datasource.password=root

# JDBC Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT AUTH
jwt.secret=mysupersecurejwtsecretkeymysupersecurejwtsecretkey
jwt.expiration=9000000

#SMS GATEWAY
messagecentral.customer.id=C-5266D8C18AE14FE
messagecentral.api.key=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJDLTUyNjZEOEMxOEFFMTRGRSIsImlhdCI6MTc3MzY0OTU3MSwiZXhwIjoxOTMxMzI5NTcxfQ.FP1jht2GLg5Cy39yCcNJ_p6WcsD_NgaO5lyT_Yw0dCZgURbjJSVsFFDbrb7V3m1_2KJleFIC01XiuYKd0_WFew

#MAIL GATEWAY
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=vaibhavrawade123@gmail.com
spring.mail.password=oxyt kdmx faku zgxj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Redis server host (localhost for WSL)
spring.redis.host=localhost
spring.redis.port=6379
# spring.redis.password=   # leave blank if Redis has no password
spring.redis.timeout=60000


#Upload File Image
file.upload-dir=C:/uploads/employees
spring.web.resources.static-locations=file:///C:/uploads/employees/


# Base URL for Display image
employee.image.base-url=http://localhost:8086/uploads/employees/